
version: '3.1'
services:
  maria-db:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    container_name: maria-db
    ports:
      - "3306:3306"
    env_file:
      - ./.env 
    networks:
      - docker-network
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    container_name: nginx
    ports:
      - "8081:8080"
    networks:
      - docker-network
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf


networks:
  docker-network:
