
version: '3.1'
services:
  maria-db:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    container_name: maria-db
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - mariadb_data:/var/lib/mysql 
      # - /home/oumaima/data/db:/var/lib/mysql
      -  ./requirements/mariadb/conf/init.sql:/etc/mysql/conf.d/init.sql 
    networks:
      - docker-network
    # volumes:
    #   - /home/oumaima/data:/var/lib/mysql
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - wordpress-php
    container_name: nginx
    ports:
      - "8081:80"
      - "443:443"
    networks:
      - docker-network
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./requirements/nginx/conf/ssl/nginx.key:/etc/nginx/ssl/nginx.key
      - ./requirements/nginx/conf/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt
      - wordpress_data:/var/www/html
  wordpress-php:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    container_name: wordpress-php
    # ports:
    #   - "8083:9000"
    environment:
      WORDPRESS_DB_HOST: maria-db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - maria-db
    volumes:
      - wordpress_data:/var/www/html
      # - /home/oumaima/data/wordpress:/var/www/html/wordpress
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  wordpress_data:
  mariadb_data:

networks:
  docker-network:
    driver: bridge
