
version: '3.1'
services:
  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    container_name: adminer
    ports:   
      - "8081:8080"
    depends_on:
      - mariadb
    networks:
      - docker-network

  ftp-server:
    build:
      context: ./requirements/bonus/ftp-server
      dockerfile: Dockerfile
    restart: always
    container_name: ftp-server
    ports:
      - "20:20"
      - "21:21"
      - "10000-10100:10000-10100"
    volumes:
      - wordpress_files:/ftpuser/wordpress_files
    networks:
      - docker-network

  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - docker-network

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - docker-network

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - wordpress-php
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network

  wordpress-php:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    container_name: wordpress-php
    ports:
      - "8888:80"
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress_files:/wordpress
    networks:
      - docker-network


volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oumaima/data/db
  wordpress_files:
    name: wordpress_files
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oumaima/data/wordpress



networks:
  docker-network:
    driver: bridge
