
version: '3.1'
services:
  adminer:
    image: adminer
    ports:   
      - "8081:8080"
    depends_on:
      - mariadb
    networks:
      - docker-network
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - docker-network

  # nginx:
  #   build:
  #     context: ./requirements/nginx
  #     dockerfile: Dockerfile
  #   restart: always
  #   depends_on:
  #     - wordpress-php
  #   container_name: nginx
  #   ports:
  #     - "443:443"
  #   networks:
  #     - docker-network
  #   volumes:
  #     - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
  #     # - wordpress_data:/var/www/html
  # wordpress-php:
    # build:
    #   context: ./requirements/wordpress
    #   dockerfile: Dockerfile
    # restart: always
    # container_name: wordpress-php
    # # ports:
    # #   - "8083:9000"
    # environment:
    #   WORDPRESS_DB_HOST: maria-db:3306
    #   WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    #   WORDPRESS_DB_USER: ${MYSQL_USER}
    #   WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    # depends_on:
    #   - maria-db
    # # volumes:
    #   # - wordpress_data:/var/www/html
    #   # - /home/oumaima/data/wordpress:/var/www/html/wordpress
    # networks:
    #   - docker-network
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5


volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oumaima/data/db
    

networks:
  docker-network:
    driver: bridge
